
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // Plain process.env access (not the strict `env()` helper) so `prisma
  // generate` doesn't hard-fail when DATABASE_URL isn't set yet — it only
  // needs a live connection for `migrate` / `db push` / `studio`.
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
